apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapproxy-api.api-fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mapproxy-api.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.mapproxyApi.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mapproxy-api.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: api
      port: {{ .Values.mapproxyApi.service.port }}
      targetPort: {{ .Values.mapproxyApi.service.port }}
